import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-gray-950 h-screen">
        <div className='p-4 text-red-400 font-semibold w-fit mx-auto absolute top-24 left-10 shadow rounded-sm shadow-red-500' > Hello, This is the light box.</div>
      </main>
    </>
  )
}
